* yum
** How to integrate into your policy
First get the policy into your masterfiles

#+beign_src sh
  export MASTERFILES=/home/nickanderson/CFEngine/masterfiles
  git clone https://github.com/nickanderson/yum.git
  cd yum
  mkdir -p $MASTERFILES/services/yum
  git archive master | tar -x -C $MASTERFILES/services/yum
#+end_src

Include def.cf into your inputs
#+begin_src cfengine
  body common control
  {
        inputs => { 
                    # Reports
                    @(cfengine_reports.inputs),
  
                    # If you want to activate this policy from autorun,
                    # then it needs to be included before autorun
                    # inptus.
                    "services/CVE_2015_0235/def.cf",
                    
                    # autorun system
                    @(services_autorun.inputs),
        };
  }
#+end_src

Ensure the features you want are enabled, and that the policy will be activated.

#+begin_src cfengine
  classes:
    "enable_yum_inventory_autorun" expression => "services_autorun";
    "enable_yum_inventory_all" expression => "any";
#+end_src

Ensure the policy is activated

In the example above I enabled the policy activation with autorun, but it can be activated manually as well.

#+begin_src cfengine
  methods:
    redhat|centos::
      "yum" usebundle => yum_inventory;
#+end_src

** yum_inventory_yum_info_yum
Inventory interesting information about yum. Currently this includes
the yum plugins (if any) which are loaded.

Variables for enabled plugins are defined and tagged for use in
CFEngine Enteprise Mission Portals Inventory interface. Classes are
defined for each loaded plugin in the form
`yum_plugin_<plugin_name>_loaded`.

Enabled by setting the class `enable_yum_inventory_yum_info_yum` or
`enable_yum_inventory_all`.

** yum_inventory_yum_repolist
Inventory interesting information about the yum repositories configured.

Variables for each enabled and disabled repository are defined and
tagged for use in CFEngine Enterprise Mission Poratls Inventory
interface. Classes are defined for each configured repo in the form
`yum_repo_<repo_id>_enabled` or `yum_repo_<repo_id>_disabled`.

Enabled by setting the class `enable_yum_inventory_yum_repolist` or
`enable_yum_inventory_all`.
